# Generated by Django 3.2.6 on 2021-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='registeration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
